
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: practice14_development

test:
  <<: *default
  database: practice14_test

production:
  <<: *default
  database: practice14_production
  username: practice14
  password: <%= ENV['PRACTICE14_DATABASE_PASSWORD'] %>
